# Generated by Django 3.1.4 on 2020-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, help_text='First Name', max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Second Name', max_length=200, null=True)),
                ('email', models.CharField(blank=True, help_text='example@example.com', max_length=200, null=True)),
                ('phone', models.CharField(help_text='+7**********', max_length=12)),
                ('size', models.CharField(blank=True, help_text='255/65/19', max_length=200, null=True)),
                ('tireName', models.CharField(blank=True, help_text='Continental', max_length=200, null=True)),
                ('tireCount', models.CharField(help_text='4', max_length=4)),
                ('platesNum', models.CharField(help_text='o000oo30', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('dateOut', models.TextField()),
                ('dateIn', models.TextField()),
                ('price', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('onCall', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
