# Generated by Django 3.1.4 on 2020-12-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201223_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dateIn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateOut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.TextField(blank=True, help_text='example@example.com', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.TextField(blank=True, help_text='First Name', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.TextField(blank=True, help_text='Second Name', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='onCall',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.TextField(blank=True, help_text='+7**********'),
        ),
        migrations.AlterField(
            model_name='client',
            name='platesNum',
            field=models.TextField(blank=True, help_text='o000oo30', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='size',
            field=models.TextField(blank=True, help_text='255/65/19', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tireCount',
            field=models.TextField(blank=True, help_text='4', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tireName',
            field=models.TextField(blank=True, help_text='Continental', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='totalPrice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
