# Generated by Django 3.1.4 on 2020-12-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20201224_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='client',
            name='car',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='clientId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.TextField(blank=True, help_text='middle Name', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='withRims',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
