# Generated by Django 3.1.4 on 2020-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20201230_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True)),
                ('clientId', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, help_text='First Name', null=True)),
                ('middle_name', models.TextField(blank=True, help_text='middle Name', null=True)),
                ('last_name', models.TextField(blank=True, help_text='Second Name', null=True)),
                ('email', models.TextField(blank=True, help_text='example@example.com', null=True)),
                ('phone', models.TextField(blank=True, help_text='+7**********')),
                ('size', models.TextField(blank=True, help_text='255/65/19', null=True)),
                ('tireName', models.TextField(blank=True, help_text='Continental', null=True)),
                ('tireCount', models.TextField(blank=True, help_text='4', null=True)),
                ('platesNum', models.TextField(blank=True, help_text='o000oo30', null=True)),
                ('car', models.TextField(blank=True, null=True)),
                ('withRims', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dateOut', models.TextField(blank=True, null=True)),
                ('dateIn', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('totalPrice', models.TextField(blank=True, null=True)),
                ('onCall', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
