# Generated by Django 3.1.4 on 2020-12-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='log',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
    ]
